version: '2'

services:
  build:
    image: ${REACTANT_IMAGE}:latest
    build:
      context: ${REACTANT_ROOT}
      dockerfile: ${REACTANT_DOCKERFILE}
      args:
        BUILD_PACKAGES: ${REACTANT_BUILD_PACKAGES}
        IMAGE: ${REACTANT_IMAGE}:latest
        MAINTAINER: ${REACTANT_MAINTAINER}
        PACKAGES: ${REACTANT_PACKAGES}
        PLATFORM: ${REACTANT_PLATFORM}
  major:
    extends: build
    image: ${REACTANT_IMAGE}:${REACTANT_MAJOR}
    build:
      args:
        IMAGE: ${REACTANT_IMAGE}:${REACTANT_MAJOR}
  minor:
    extends: build
    image: ${REACTANT_IMAGE}:${REACTANT_MAJOR}.${REACTANT_MINOR}
    build:
      args:
        IMAGE: ${REACTANT_IMAGE}:${REACTANT_MAJOR}.${REACTANT_MINOR}
  patch:
    extends: build
    image: ${REACTANT_IMAGE}:${REACTANT_MAJOR}.${REACTANT_MINOR}.${REACTANT_PATCH}
    build:
      args:
        IMAGE: ${REACTANT_IMAGE}:${REACTANT_MAJOR}.${REACTANT_MINOR}.${REACTANT_PATCH}
